### ISSUE TITLE
Does this work with Unity 5 or not?

### ISSUE THREAD

**Issue by whatthewhatwhat** [DragonBones/DragonBonesUnity#11]
Hey, the website says that DB is compatible with Unity but this stuff is just a mess. No documentation, I can't tell if it works or if I'm just not doing something right.

**Comment by maxin0628** [comment]
yes it works with unity5, but its only compatible with the data of DB 2.4,
not the latest 4.0

there is a demo in the project, if you are using the old data, you can try
it out.

**Comment by whatthewhatwhat** [comment]
Sigh, ok... not a ton of wasted time I guess... I don't know why the DB website says that it's compatible with Unity then.

I tried the demo thing but it just seemed empty.

**Comment by maxin0628** [comment]
no, it's not empty. double hit any .unity file will not open any scene for you automatically, open the scene in project by yourself, then run, make sense?

and about compatibility, this runtime is a volunteer contribution from my project. to get 4.0 support, maybe you need to wait my next db 4.0 game, cause i'm still using 2.4. but this version's runtime works well so far.  or you can contact official team of DB and let them support unity officially.

**Comment by drzaal** [comment]
Crap. I'm going to offer to help aren't I. You interested in having someone update for 4.5 data?

**Comment by maxin0628** [comment]
no you don't need to, as far as I know official guys had begun it, and will finish soon...just keep an eye on their website....
